- utils/gcs_helper.py
- 기존 코드 설계는 버킷이 1개일 때 진행됨
- 프로젝트 진행에 따라 버킷의 수가 늘어나면서 객체를 새로 생성해야하는 불편함 존재
- 따라서 하나의 객체로 버킷을 바꿔가면서 사용할 수 있도록 코드 수정
> [Update]: GCS Helper 버킷 변경 기능 추가

- crawler/maplegg_user_crawler.py
> [Feat]: 리부트 서버 추가

- modeling/config/inference.json
- modeling/config/mfconfig.json
- modeling/dataloader/dataloader.py
- modeling/dataloader/preprocess.py
- modeling/dataset/dataset.py
- modeling/inference.py
- modeling/model/get_model.py
- modeling/model/newMF.py
- modeling/train.py
- modeling/trainer/newMF_trainer.py
- modeling/utilities/util.py
- 학습 데이터 형태 변경 (이름 -> index) 로 인한 리팩토링 진행
- 큰 틀은 똑같고 세부적으로 약간 바뀜
- preprocessing 과정 제거
- 착용하지 않은 아이템 학습하지 않도록 변경
- `sys.path.append(
os.path.dirname(
os.path.abspath(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
)
)` 코드 모두 제거, 경로 import방식 수정
- 따라서 실행 시 `python3 train.py` 가 아니라 상위 폴더에서 `python3 -m modeling.train` 으로 실행해야함
> [Refactor]: newMF 리팩토링 진행

- crawler/user_img_detail_crawler.py
- img를 gcs에 저장하지 않아 컬럼하나가 추가되지 않아 에러 발생
- None으로 채워넣어 해결
> [Fix]: user detail crawler 버그 수정

- modeling/config/MCN_config.json
- modeling/dataloader/dataloader.py
- modeling/dataloader/preprocess.py
- modeling/dataset/MCN_dataset.py
- modeling/model/__init__.py
- modeling/model/get_model.py
- modeling/model/mcn.py
- modeling/model/resnet.py
- modeling/train.py
- modeling/trainer/MCN_trainer.py
- modeling/trainer/__init__.py
- modeling/trainer/get_trainer.py
- modeling/trainer/loss.py
- modeling/trainer/scheduler.py
- modeling/utils/__init__.py
- modeling/utils/big_query_helper.py
- modeling/utils/gcs_helper.py
향후 mcn_trainer에 optimizer가 config에 따라 들어가도록 수정할 필요가 있음
> Modeling mcn

- modeling/config/MCN_config.json
- modeling/model/get_model.py
- modeling/model/mcn.py
- mcn모델에 pretrained 파라미터를 추가해 원하는대로 조정할 수 있도록 변경
> [Feat]: pretrained 옵션 추가

- backend/src/main.py
> [Fix]: CORS error fixed

- modeling/dataset/MCN_dataset.py
- modeling/model/get_model.py
- modeling/model/mcn.py
- modeling/model/resnet.py
- modeling/train.py
- modeling/trainer/MCN_trainer.py
- black 적용 안되어있어서 적용
- dataset get item return이 변경되었는데 type 명시는 변환 안되어있어서 변경
> [Chore]: MCN 모델 formatter 적용

- modeling/dataset/MCN_dataset.py
- modeling/dataset/get_dataset.py
- modeling/dataset/newMF_dataset.py
- modeling/train.py
- preprocessing/user_MCN.py
- 모든 아이템 이미지에 대한 텐서를 미리 제작
- get item에서는 해당 텐서를 인덱스로 가져오기만 함
- 모든 데이터 한바퀴 돌 때 1시간 -> 10분 으로 6배가량 시간 단축
> [Feat]: MCN 학습 속도 개선

- backend/src/database/init_db.py
- backend/src/database/models/Items.py
- backend/src/database/schemas/items.py
- 추가적인 보안 설정을 위한 init_db.py 수정
- index를 추가한 버전으로 변경하며 item schema 변경
- category에 따라 불러오는 get 요청에서 top 호출 시  overall 아이템도 같이 불러오게 수정
> Back mongodborm

- front/src/pages/LandingPage_ver2/LandingPage.css
- front/src/pages/LandingPage_ver2/components/GoCodiDiagnosis.js
- front/src/pages/LandingPage_ver2/components/GoCodiRec.js
> [Fix]: FAB 버튼이 그림자를 가려 이상해지는 현상 수정

- backend/src/AI/models/model_object/newMF.py
> [Fix]: newMF 모델 최신버전으로 업데이트

- backend/Dockerfile
- front/Dockerfile
- front, back 도커파일 완성.
- 해당 Dockerfile로 image를 생성하고 GCP를 이용해서 배포
> [Feat]: 배포를 위한 Dockerfile 업로드

- front/src/pages/PreferenceRecommendPage/PreferenceRecommendPage.js
- front/src/pages/PreferenceRecommendPage/components/GoCodiRecResult.js
- (PRP) Add navigate button that brings you to result page
- (LP) 폰트 색, 크기 변경
> [Update]: PRP-Result page 이동 버튼 / LP-색 변경

- preprocessing/user_MCN.py
- 기존 장비가 모두 동일해도 다른 유저가 착용했다면 학습에 사용 했던 것을 장비가 모두 동일한 경우는 하나만 고려하도록 변경
- 착용하지 않은 부위가 4개 이상인 경우 학습하지 않도록 변경
> [Update]: 학습 데이터 조건 변경

- modeling/config/MCN_config.json
- modeling/config/inference.json
- modeling/model/get_model.py
- modeling/model/mcn.py
- modeling/model/resnet.py
- modeling/train.py
- modeling/trainer/MCN_trainer.py
- resnet을 옵션으로 설정할 수 있게 변경
- 모델이 5개의 부위만 연관성을 계산하던 것을 7개 전부 보도록 수정
> [Feat]: 모델 수정

- modeling/trainer/optimizer.py
> [Feat]: optimizer 선택 추가

- front/src/pages/CodiDiagnosisPage/CodiDiagnosisPage.css
- front/src/pages/CodiDiagnosisPage/CodiDiagnosisPage.js
- front/src/pages/CodiDiagnosisPage/components/GetDiagnosisResult.js
- front/src/pages/CodiDiagnosisPage/components/ShowDiagnosisResult.js
> [Feat]: 코디 진단 결과 점수 보이기

- backend/src/AI/config/model_config.py
- backend/src/AI/inference.py
- backend/src/AI/models/model_object/mcn.py
- backend/src/AI/models/model_object/resnet.py
- backend/src/routers/inference_router.py
> Backend mcn inference

- front/src/pages/About/components/MemberStepper.js
> [Update]: Member Stepper 배경 색 맞추기

- backend/src/AI/config/model_config.py
- backend/src/AI/image_processing.py
- backend/src/AI/inference.py
- backend/src/AI/models/model_object/__init__.py
- backend/src/AI/models/model_object/mcn_dataset.py
- torch의 Dataset과 Dataloader를 활용하여 속도 향상
- 기존보다 약 3배가량 빨라짐
- 추가적으로 type hint 조금 달아줌
> [Update]: MCN inference 속도 향상

- front/src/components/CodiPartButton.js
- front/src/components/CodiSimulator.js
- front/src/index.js
- front/src/pages/About/components/MemberStepper.js
- front/src/pages/CodiDiagnosisPage/CodiDiagnosisPage.js
- front/src/pages/CodiDiagnosisPage/components/CodiPartInputs.js
- front/src/pages/CodiDiagnosisPage/components/GetDiagnosisResult.js
- front/src/pages/PreferenceRecommendPage/PreferenceRecommendPage.js
- front/src/pages/PreferenceRecommendPage/components/CodiPartInputs.js
- front/src/pages/PreferenceRecommendPage/components/GoCodiRecResult.js
- front/src/pages/PreferenceRecommendPage/components/InfoTextAndVideo.js
- front/src/pages/PreferenceRecommendResultPage/PreferenceRecommendResultPage.js
- front/src/pages/PreferenceRecommendResultPage/components/AllCodiPartButton.js
- front/src/pages/PreferenceRecommendResultPage/components/AllParts.js
- front/src/pages/PreferenceRecommendResultPage/components/BestCodi.js
- front/src/pages/PreferenceRecommendResultPage/components/BestCodiTopThree.js
- front/src/pages/PreferenceRecommendResultPage/components/FixCodiPartButton.js
- front/src/pages/PreferenceRecommendResultPage/components/RetryButton.js
- 콘솔로그 삭제 (장원준 ㅡㅡ)
- 사용하지 않는 변수들 삭제
- 코디 추천 들어갔을 때 기본 버튼 비활성화
> [Fix]: 코디 추천 들어갔을 때 기본 버튼 비활성화

- modeling/config/simple_MCN_config.json
- modeling/dataloader/preprocess.py
- modeling/dataset/MCN_dataset.py
- modeling/dataset/get_dataset.py
- modeling/model/__init__.py
- modeling/model/basic_cnn.py
- modeling/model/get_model.py
- modeling/train.py
- modeling/trainer/MCN_trainer.py
- modeling/trainer/__init__.py
- modeling/trainer/get_trainer.py
- modeling/trainer/simple_mcn_trainer.py
- 내맘대로 Simple MCN이라고 이름 붙임
- 1 에폭당 약 20분 정도의 시간 소요
- 기존 MCN 모델의 정확한 validation을 위해 dataset 수정
- 학습을 위해서는 MCN_dataset.py의 image resize를 24로 변경해주어야 함.
> [Feat]: 가벼워진 MCN 제작

- backend/src/AI/image_processing.py
- backend/src/AI/inference/__init__.py
- backend/src/AI/inference/mcn_inference.py
- backend/src/AI/inference/newmf_inference.py
- backend/src/AI/init_model.py
- backend/src/database/init_db.py
- backend/src/database/models/Feedbacks.py
- backend/src/database/models/crud_item.py
- backend/src/routers/diagnosis_router.py
- backend/src/routers/feedback_router.py
- backend/src/routers/inference_router.py
- AsyncIOMotorClient를 이용한 비동기 처리
- inference가 너무 더러워져서 폴더로 만듦
> [Update]: Mongo db 비동기 설정, 폴더 구조 개편

- README.md
- backend/src/AI/__init__.py
- backend/src/AI/config/model_config.py
- backend/src/AI/image32_processing.py
- backend/src/AI/inference/__init__.py
- backend/src/AI/inference/ae_inference.py
- backend/src/AI/init_model.py
- backend/src/AI/models/model_object/__init__.py
- backend/src/AI/models/model_object/ae_dataset.py
- backend/src/AI/models/model_object/ae_predictor.py
- backend/src/AI/models/model_object/auto_encoder.py
- backend/src/main.py
- backend/src/routers/inference_router.py
- front/src/pages/PreferenceRecommendResultPage/PreferenceRecommendResultPage.js
- 오토 인코더 모델 추가
- inference 모델 통일
- .env에서 모델을 지정해주면 해당 모델로 inference 수행
> Backend inference ae

- modeling/test/__main__.py
- modeling/test/load_data.py
- modeling/test/main.py
- modeling/test/test_dataset.py
- modeling/test/tester.py
- 모델 종류와 관계 없이 모델 간 비교 가능
- inference의 결과를 수치로 표현할 수 있게 됨
> [Feat]: test를 이용한 모델 평가 

- front/src/App.js
- front/src/components/CodiPartButton.js
- front/src/components/GoReviewPage.css
- front/src/components/GoReviewPage.js
- front/src/pages/CodiDiagnosisPage/CodiDiagnosisPage.js
- front/src/pages/CodiDiagnosisPage/components/CodiPartInputs.js
- front/src/pages/CodiDiagnosisPage/components/GetDiagnosisResult.js
- front/src/pages/PreferenceRecommendPage/PreferenceRecommendPage.js
- front/src/pages/PreferenceRecommendPage/components/BasicPopover.js
- front/src/pages/PreferenceRecommendPage/components/CodiPartInputs.js
- front/src/pages/PreferenceRecommendPage/components/GoCodiRecResult.js
- front/src/pages/PreferenceRecommendResultPage/PreferenceRecommendResultPage.js
- 모든 페이지 하단에 바로 리뷰 쓰러 가기 버튼 생성
- CDP->PRP 이동 시 바로 추천 안 되는 오류 해결
- 상의가 한벌옷일 때 하의 클릭 시 경고
- CDP, PRP에서 결과 받기 버튼 항상 활성화 시켜놓고 조건 미충족일 때 클릭 시 경고
> [Front] 리뷰 바로 가기 버튼, 기타 오류 해결

- front/src/App.js
- front/src/components/CodiPartButton.js
- front/src/pages/CodiDiagnosisPage/components/GetDiagnosisResult.js
- front/src/pages/PreferenceRecommendPage/PreferenceRecommendPage.js
- front/src/pages/PreferenceRecommendPage/components/CodiPartInputs.js
> [Fix]: 같은 버튼 여러번 클릭 시 여러번 업데이트 되는 현상 해결

- front/src/components/CodiPartButton.js
- front/src/components/GoReviewPage.js
- front/src/pages/PreferenceRecommendPage/PreferenceRecommendPage.js
- front/src/pages/PreferenceRecommendPage/components/GoCodiRecResult.js
- front/src/pages/PreferenceRecommendResultPage/PreferenceRecommendResultPage.css
- front/src/pages/PreferenceRecommendResultPage/components/RetryButton.js
- PRP: 모든 부위 선택 시 팝업 창 문구 변경 #135 
(기존: 7개 다 선택해도 "2개 이상 선택해주세요." -> 변경: "모든 부위 선택 시 추천 불가능합니다.")
(+a로 최소 두 부위 -> 최소 세 부위로 멘트 수정)
- PRRP: 리뷰쓰러가기 링크 센터 정렬, 코디 다시 추천 받기 버튼 연결 페이지 변경 #115 
(코디 다시 추천 받기 버튼의 경우 기존 메인 페이지로 연결되던걸 PRP로 선택 상태 그대로 고정해서 다시 돌려주는 것으로 변경 -> 불편하다는 유저 피드백 반영)
> [Fix]: PRP, PRRP 업데이트
